---
base_packages:                                                                                                                                                              
  - net-tools                                                                                                                                                             
  - htop                                                                                                                                                              
  - atop                                                                                                                                                          
  - neofetch                                                                                                                                                  
